/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : bigint,
  'action' : string,
  'userId' : Principal,
  'entityId' : bigint,
  'timestamp' : bigint,
  'details' : [] | [string],
  'entityType' : string,
}
export interface CustomReport {
  'selectedLocations' : Array<Location>,
  'combinedTotals' : Array<[string, bigint]>,
}
export interface Customer {
  'id' : bigint,
  'zip' : string,
  'city' : string,
  'name' : string,
  'equipmentList' : Array<bigint>,
  'email' : string,
  'state' : string,
  'address' : string,
  'notes' : [] | [string],
  'phone' : string,
  'serviceHistory' : Array<bigint>,
}
export interface CustomerEquipment {
  'id' : bigint,
  'model' : string,
  'purchaseDate' : [] | [bigint],
  'equipmentType' : string,
  'installDate' : [] | [bigint],
  'serialNumber' : string,
  'warrantyExpiry' : [] | [bigint],
  'customerId' : bigint,
  'brand' : string,
  'location' : string,
}
export interface GasketInfo {
  'glassFreezer' : string,
  'freezer' : string,
  'locationId' : bigint,
  'outsideDressTable' : string,
  'insideDress' : string,
  'cooler' : string,
  'fryFreezer' : string,
  'grillBox' : string,
}
export interface Item {
  'id' : bigint,
  'sku' : string,
  'unitOfMeasure' : string,
  'supplierIds' : Array<bigint>,
  'reorderPoint' : bigint,
  'maxStock' : bigint,
  'subcategory' : string,
  'cost' : number,
  'name' : string,
  'unit' : string,
  'description' : string,
  'sellPrice' : number,
  'isActive' : boolean,
  'customFields' : Array<[string, string]>,
  'variantOf' : [] | [bigint],
  'barcode' : [] | [string],
  'category' : string,
  'qrCode' : [] | [string],
}
export interface Location {
  'id' : bigint,
  'filterRequirements' : Array<[string, bigint]>,
  'active' : boolean,
  'name' : string,
  'completed' : boolean,
  'beltRequirements' : Array<[string, bigint]>,
  'isActive' : boolean,
  'zones' : Array<string>,
  'address' : [] | [string],
  'managerId' : [] | [bigint],
  'locationType' : { 'JobSite' : null } |
    { 'SecondaryStorage' : null } |
    { 'Warehouse' : null } |
    { 'ServiceTruck' : null },
}
export interface MaintenanceRecord {
  'id' : bigint,
  'completedDate' : [] | [bigint],
  'status' : { 'Overdue' : null } |
    { 'Scheduled' : null } |
    { 'Cancelled' : null } |
    { 'InProgress' : null } |
    { 'Completed' : null },
  'scheduledDate' : bigint,
  'cost' : number,
  'partsUsed' : Array<WorkOrderPart>,
  'equipmentType' : string,
  'technicianId' : bigint,
  'notes' : [] | [string],
  'workPerformed' : string,
  'equipmentId' : bigint,
}
export interface OrderItem {
  'itemId' : bigint,
  'name' : string,
  'quantity' : bigint,
}
export interface PurchaseOrder {
  'id' : bigint,
  'status' : { 'Sent' : null } |
    { 'Closed' : null } |
    { 'Acknowledged' : null } |
    { 'PartiallyReceived' : null } |
    { 'Draft' : null } |
    { 'Received' : null },
  'createdDate' : bigint,
  'totalCost' : number,
  'receivedDate' : [] | [bigint],
  'notes' : [] | [string],
  'items' : Array<PurchaseOrderItem>,
  'expectedDate' : [] | [bigint],
  'supplierId' : bigint,
}
export interface PurchaseOrderItem {
  'itemId' : bigint,
  'receivedQuantity' : bigint,
  'notes' : [] | [string],
  'quantity' : bigint,
  'unitCost' : number,
}
export interface ReorderAlert {
  'id' : bigint,
  'status' : { 'Ordered' : null } |
    { 'Acknowledged' : null } |
    { 'Active' : null } |
    { 'Resolved' : null },
  'itemId' : bigint,
  'reorderPoint' : bigint,
  'createdDate' : bigint,
  'suggestedQuantity' : bigint,
  'locationId' : bigint,
  'currentStock' : bigint,
}
export interface ServiceKit {
  'id' : bigint,
  'name' : string,
  'totalCost' : number,
  'description' : string,
  'estimatedLaborHours' : number,
  'category' : string,
  'parts' : Array<ServiceKitPart>,
}
export interface ServiceKitPart { 'quantity' : bigint, 'partId' : bigint }
export interface StagingReport {
  'locationId' : bigint,
  'items' : Array<[string, bigint]>,
  'locationName' : string,
}
export interface StockLevel {
  'bin' : [] | [string],
  'itemId' : bigint,
  'beginningInventory' : [] | [bigint],
  'zone' : [] | [string],
  'lastUpdated' : bigint,
  'locationId' : bigint,
  'quantity' : bigint,
  'currentStock' : [] | [bigint],
  'receive1' : [] | [bigint],
  'receive2' : [] | [bigint],
  'receive3' : [] | [bigint],
}
export interface Supplier {
  'id' : bigint,
  'contactName' : string,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'website' : [] | [string],
  'leadTimeDays' : bigint,
  'address' : string,
  'rating' : number,
  'paymentTerms' : string,
  'phone' : string,
}
export interface Technician {
  'id' : bigint,
  'assignedTruckId' : [] | [bigint],
  'name' : string,
  'role' : string,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
  'skills' : Array<string>,
}
export interface Transaction {
  'id' : bigint,
  'itemId' : bigint,
  'transactionType' : { 'Loss' : null } |
    { 'Issued' : null } |
    { 'Transfer' : null } |
    { 'Returned' : null } |
    { 'Damaged' : null } |
    { 'Adjustment' : null } |
    { 'Receipt' : null },
  'toLocationId' : [] | [bigint],
  'userId' : Principal,
  'fromLocationId' : [] | [bigint],
  'notes' : [] | [string],
  'timestamp' : bigint,
  'quantity' : bigint,
  'relatedOrderId' : [] | [bigint],
  'reason' : string,
}
export interface UserProfile { 'name' : string }
export interface WorkOrder {
  'id' : bigint,
  'completedDate' : [] | [bigint],
  'status' : { 'Invoiced' : null } |
    { 'Scheduled' : null } |
    { 'Cancelled' : null } |
    { 'InProgress' : null } |
    { 'Completed' : null },
  'title' : string,
  'scheduledDate' : bigint,
  'laborHours' : number,
  'totalCost' : number,
  'description' : string,
  'locationId' : bigint,
  'technicianId' : bigint,
  'notes' : [] | [string],
  'customerId' : bigint,
  'priority' : { 'Low' : null } |
    { 'High' : null } |
    { 'Medium' : null } |
    { 'Emergency' : null },
  'assignedParts' : Array<WorkOrderPart>,
}
export interface WorkOrderPart {
  'totalCost' : number,
  'quantity' : bigint,
  'partId' : bigint,
  'unitCost' : number,
}
export interface _SERVICE {
  'createCustomer' : ActorMethod<[Customer], bigint>,
  'createCustomerEquipment' : ActorMethod<[CustomerEquipment], bigint>,
  'createItem' : ActorMethod<[string, string, string], undefined>,
  'createLocation' : ActorMethod<
    [string, Array<[string, bigint]>, Array<[string, bigint]>],
    undefined
  >,
  'createMaintenanceRecord' : ActorMethod<[MaintenanceRecord], bigint>,
  'createPurchaseOrder' : ActorMethod<[PurchaseOrder], bigint>,
  'createReorderAlert' : ActorMethod<[ReorderAlert], bigint>,
  'createServiceKit' : ActorMethod<[ServiceKit], bigint>,
  'createSupplier' : ActorMethod<[Supplier], bigint>,
  'createTechnician' : ActorMethod<[Technician], bigint>,
  'createTransaction' : ActorMethod<[Transaction], bigint>,
  'createWorkOrder' : ActorMethod<[WorkOrder], bigint>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteCustomerEquipment' : ActorMethod<[bigint], undefined>,
  'deleteGasketInfo' : ActorMethod<[bigint], undefined>,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'deleteLocation' : ActorMethod<[bigint], undefined>,
  'deletePurchaseOrder' : ActorMethod<[bigint], undefined>,
  'deleteServiceKit' : ActorMethod<[bigint], undefined>,
  'deleteSupplier' : ActorMethod<[bigint], undefined>,
  'deleteTechnician' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'deleteWorkOrder' : ActorMethod<[bigint], undefined>,
  'generateCustomReport' : ActorMethod<[Array<bigint>], CustomReport>,
  'generateOrder' : ActorMethod<[], Array<OrderItem>>,
  'generateStagingReport' : ActorMethod<[], Array<StagingReport>>,
  'getActiveReorderAlerts' : ActorMethod<[], Array<ReorderAlert>>,
  'getAllActivityLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getAllCustomerEquipments' : ActorMethod<[], Array<CustomerEquipment>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllGasketInfos' : ActorMethod<[], Array<GasketInfo>>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getAllLocations' : ActorMethod<[], Array<Location>>,
  'getAllMaintenanceRecords' : ActorMethod<[], Array<MaintenanceRecord>>,
  'getAllPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getAllReorderAlerts' : ActorMethod<[], Array<ReorderAlert>>,
  'getAllServiceKits' : ActorMethod<[], Array<ServiceKit>>,
  'getAllStockLevels' : ActorMethod<[], Array<StockLevel>>,
  'getAllSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getAllTechnicians' : ActorMethod<[], Array<Technician>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerEquipment' : ActorMethod<[bigint], [] | [CustomerEquipment]>,
  'getCustomerEquipmentByCustomer' : ActorMethod<
    [bigint],
    Array<CustomerEquipment>
  >,
  'getLocationGasketInfo' : ActorMethod<[bigint], [] | [GasketInfo]>,
  'getMaintenanceRecord' : ActorMethod<[bigint], [] | [MaintenanceRecord]>,
  'getMaintenanceRecordsByEquipment' : ActorMethod<
    [bigint],
    Array<MaintenanceRecord>
  >,
  'getPurchaseOrder' : ActorMethod<[bigint], [] | [PurchaseOrder]>,
  'getPurchaseOrdersBySupplier' : ActorMethod<[bigint], Array<PurchaseOrder>>,
  'getServiceKit' : ActorMethod<[bigint], [] | [ServiceKit]>,
  'getStockLevelByItemId' : ActorMethod<[bigint], [] | [StockLevel]>,
  'getSupplier' : ActorMethod<[bigint], [] | [Supplier]>,
  'getTechnician' : ActorMethod<[bigint], [] | [Technician]>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getTransactionsByItem' : ActorMethod<[bigint], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkOrder' : ActorMethod<[bigint], [] | [WorkOrder]>,
  'getWorkOrdersByCustomer' : ActorMethod<[bigint], Array<WorkOrder>>,
  'getWorkOrdersByTechnician' : ActorMethod<[bigint], Array<WorkOrder>>,
  'listUsers' : ActorMethod<[], Array<Principal>>,
  'logActivity' : ActorMethod<
    [string, string, bigint, [] | [string]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLocationGasketInfo' : ActorMethod<[bigint, GasketInfo], undefined>,
  'searchGasketLocations' : ActorMethod<[string], Array<Location>>,
  'searchLocations' : ActorMethod<[string], Array<Location>>,
  'seedAllData' : ActorMethod<[], undefined>,
  'updateCustomer' : ActorMethod<[bigint, Customer], undefined>,
  'updateCustomerEquipment' : ActorMethod<
    [bigint, CustomerEquipment],
    undefined
  >,
  'updateItem' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateLocation' : ActorMethod<
    [bigint, string, Array<[string, bigint]>, Array<[string, bigint]>],
    undefined
  >,
  'updateLocationActiveStatus' : ActorMethod<[bigint, boolean], undefined>,
  'updateLocationCompletionStatus' : ActorMethod<[bigint, boolean], undefined>,
  'updateMaintenanceRecord' : ActorMethod<
    [bigint, MaintenanceRecord],
    undefined
  >,
  'updatePurchaseOrder' : ActorMethod<[bigint, PurchaseOrder], undefined>,
  'updateReorderAlertStatus' : ActorMethod<
    [
      bigint,
      { 'Ordered' : null } |
        { 'Acknowledged' : null } |
        { 'Active' : null } |
        { 'Resolved' : null },
    ],
    undefined
  >,
  'updateServiceKit' : ActorMethod<[bigint, ServiceKit], undefined>,
  'updateStockLevel' : ActorMethod<
    [
      bigint,
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'updateSupplier' : ActorMethod<[bigint, Supplier], undefined>,
  'updateTechnician' : ActorMethod<[bigint, Technician], undefined>,
  'updateWorkOrder' : ActorMethod<[bigint, WorkOrder], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];